image:
    - Visual Studio 2019
    - Visual Studio 2017
    - Ubuntu
    - macOS

for:
-
    matrix:
        only:
            - image: Visual Studio 2019
            - image: Visual Studio 2017
    build_script:
        - C:\\Python36-x64\\python Bootstrap.py

build_script:
        - ./Bootstrap.py
